version: '3.8'

services:
  data-base:
    image: postgres:14-alpine
    container_name: taskTest-db
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=taskTest-db
      - POSTGRES_USER=name
      - POSTGRES_PASSWORD=test
    healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U name -d taskTest-db" ]
          interval: 5s
          timeout: 2s
          retries: 3

  task-test:
    build:
      context: .
    container_name: task-test
    ports:
      - "8080:8080"
    depends_on:
      data-base:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://taskTest-db:5432/taskTest-db
      - SPRING_DATASOURCE_USERNAME=name
      - SPRING_DATASOURCE_PASSWORD=test

